Changed to base on native 5.6 packaging
* Made changes to update for 5.7
* Included various fixes by Bjoern Boschman

diff --git a/debian/mysql-server-5.7.mysql.init b/debian/mysql-server-5.7.mysql.init
--- a/debian/mysql-server-5.7.mysql.init
+++ b/debian/mysql-server-5.7.mysql.init
@@ -8,199 +8,177 @@
 # Should-Stop:       $network $time
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: Start/ Stop MySQL Community Server daemon
-# Description:       This service script facilitates startup and shutdown of
-#                    mysqld daemon throught its wrapper script mysqld_safe
+# Short-Description: Start and stop the mysql database server daemon
+# Description:       Controls the main MySQL database server daemon "mysqld"
+#                    and its wrapper script "mysqld_safe".
 ### END INIT INFO
 #
+set -e
+set -u
+${DEBIAN_SCRIPT_DEBUG:+ set -v -x}
 
-# Copyright (c) 2015, Oracle and/or its affiliates. All rights reserved.
-#
-# This program is free software; you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; version 2 of the License.
-#
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-#
-# You should have received a copy of the GNU General Public License
-# along with this program; if not, write to the Free Software
-# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
+test -x /usr/bin/mysqld_safe || exit 0
 
 . /lib/lsb/init-functions
 
+SELF=$(cd $(dirname $0); pwd -P)/$(basename $0)
+CONF=/etc/mysql/my.cnf
+MYADMIN="/usr/bin/mysqladmin --defaults-file=/etc/mysql/debian.cnf"
+
+# priority can be overriden and "-s" adds output to stderr
+ERR_LOGGER="logger -p daemon.err -t /etc/init.d/mysql -i"
+
+# Safeguard (relative paths, core dumps..)
 cd /
 umask 077
 
-# In case server is taking more to start or stop increase the timeout here
-STARTTIMEOUT=180
-STOPTIMEOUT=60
+# mysqladmin likes to read /root/.my.cnf. This is usually not what I want
+# as many admins e.g. only store a password without a username there and
+# so break my scripts.
+export HOME=/etc/mysql/
 
-VERSION=$(mysqld --version | grep mysqld | cut -d' ' -f4)
-
-get_mysql_option() {
-	RESULT=$(my_print_defaults "$1" | sed -n "s/^--$2=//p" | tail -n 1)
-	if [ -z "$RESULT" ];
-	then
-		RESULT="$3"
-	fi
-	echo $RESULT
+## Fetch a particular option from mysql's invocation.
+#
+# Usage: void mysqld_get_param option
+mysqld_get_param() {
+	/usr/sbin/mysqld --print-defaults \
+		| tr " " "\n" \
+		| grep -- "--$1" \
+		| tail -n 1 \
+		| cut -d= -f2
 }
 
-get_running () {
-	PIDFILE=$(get_mysql_option mysqld_safe pid-file "")
-	if [ -z "$PIDFILE" ];
-	then
-		PIDFILE=$(get_mysql_option mysqld pid-file "$MYSQLDATA/$(hostname).pid")
-	fi
-	if [ -e "$PIDFILE" ] && [ -d "/proc/$(cat "$PIDFILE")" ];
-	then
-		echo 1
-	else
-		echo 0
-	fi
+## Do some sanity checks before even trying to start mysqld.
+sanity_checks() {
+  # check for config file
+  if [ ! -r /etc/mysql/my.cnf ]; then
+    log_warning_msg "$0: WARNING: /etc/mysql/my.cnf cannot be read. See README.Debian.gz"
+    echo                "WARNING: /etc/mysql/my.cnf cannot be read. See README.Debian.gz" | $ERR_LOGGER
+  fi
+
+  # check for diskspace shortage
+  datadir=`mysqld_get_param datadir`
+  if LC_ALL=C BLOCKSIZE= df --portability $datadir/. | tail -n 1 | awk '{ exit ($4>4096) }'; then
+    log_failure_msg "$0: ERROR: The partition with $datadir is too full!"
+    echo                "ERROR: The partition with $datadir is too full!" | $ERR_LOGGER
+    exit 1
+  fi
 }
 
-verify_server () {
-	TIMEOUT=0
-	if [ "${1}" = "start" ];
-	then
-		TIMEOUT=${STARTTIMEOUT}
-	elif [ "${1}" = "stop" ];
-	then
-		TIMEOUT=${STOPTIMEOUT}
-	fi
+## Checks if there is a server running and if so if it is accessible.
+#
+# check_alive insists on a pingable server
+# check_dead also fails if there is a lost mysqld in the process list
+#
+# Usage: boolean mysqld_status [check_alive|check_dead] [warn|nowarn]
+mysqld_status () {
+    ping_output=`$MYADMIN ping 2>&1`; ping_alive=$(( ! $? ))
 
-	COUNT=0
-	while [ ${COUNT} -lt ${TIMEOUT} ];
-	do
-		COUNT=$(( COUNT+1 ))
-		echo -n .
-		if [ "${1}" = "start" ] && [ "$(get_running)" = 1 ];
-		then
-			if [ -z ${2} ];
-			then
-				echo
-			fi
-			return 0
-		fi
-		if [ "${1}" = "stop" ] && [ "$(get_running)" = 0 ];
-		then
-			if [ -z ${2} ];
-			then
-				echo
-			fi
-			return 0
-		fi
-		sleep 1
-	done
-	return 1
+    ps_alive=0
+    pidfile=`mysqld_get_param pid-file`
+    if [ -f "$pidfile" ] && ps `cat $pidfile` >/dev/null 2>&1; then ps_alive=1; fi
+    
+    if [ "$1" = "check_alive"  -a  $ping_alive = 1 ] ||
+       [ "$1" = "check_dead"   -a  $ping_alive = 0  -a  $ps_alive = 0 ]; then
+	return 0 # EXIT_SUCCESS
+    else
+  	if [ "$2" = "warn" ]; then
+  	    echo -e "$ps_alive processes alive and '$MYADMIN ping' resulted in\n$ping_output\n" | $ERR_LOGGER -p daemon.debug
+	fi
+  	return 1 # EXIT_FAILURE
+    fi
 }
 
-case "$1" in
+#
+# main()
+#
+
+case "${1:-''}" in
   'start')
-	if [ "$(get_running)" -eq 1 ];
-	then
-		log_action_msg "A MySQL Server is already started"
+	sanity_checks;
+	# Start daemon
+	log_daemon_msg "Starting MySQL database server" "mysqld"
+	if mysqld_status check_alive nowarn; then
+	   log_progress_msg "already running"
+	   log_end_msg 0
 	else
-		MYSQLRUN=/var/run/mysqld
-		MYSQLDATA=$(get_mysql_option mysqld datadir "/var/lib/mysql")
-		MYSQLFILES=/var/lib/mysql-files
-		MYSQLLOG=/var/log/mysql
+	    # Could be removed during boot
+	    test -e /var/run/mysqld || install -m 755 -o mysql -g root -d /var/run/mysqld
 
-		if [ ! -d ${MYSQLDATA} -a ! -L ${MYSQLDATA} ];
-		then
-			mkdir ${MYSQLDATA}
-			chown mysql:mysql ${MYSQLDATA}
-			chmod 750 ${MYSQLDATA}
-		fi
+	    # Start MySQL! 
+  	    su - mysql -s /bin/sh -c "/usr/bin/mysqld_safe > /dev/null 2>&1 &"
 
-		if [ ! -d ${MYSQLFILES} -a ! -L ${MYSQLFILES} ];
-		then
-			mkdir ${MYSQLFILES}
-			chown mysql:mysql ${MYSQLFILES}
-			chmod 770 ${MYSQLFILES}
-		fi
-
-		if [ ! "$(ls -A ${MYSQLDATA})" ] && [ -d ${MYSQLFILES} ];
-		then
-			su - mysql -s /bin/bash -c "/usr/sbin/mysqld --initialize-insecure=on 2>&1 > /dev/null"
-			su - mysql -s /bin/bash -c "/usr/sbin/mysqld --log_error_verbosity=2 2>&1 > /dev/null &"
-			verify_server start no-newline
-			mysql -e "INSTALL PLUGIN auth_socket SONAME 'auth_socket.so'"
-			mysql -e "USE mysql; UPDATE user SET plugin='auth_socket' WHERE user='root'"
-			mysqladmin shutdown
-		fi
-
-		if [ -x /usr/bin/mysql_ssl_rsa_setup -a ! -e "${MYSQLDATA}/server-key.pem" ];
-		then
-			/usr/bin/mysql_ssl_rsa_setup --datadir="${MYSQLDATA}" --uid=mysql >/dev/null 2>&1
-		fi
-
-		if [ ! -d ${MYSQLLOG} -a ! -L ${MYSQLLOG} ];
-		then
-			mkdir ${MYSQLLOG}
-			chown mysql:adm ${MYSQLLOG}
-			chmod 750 ${MYSQLLOG}
-			touch ${MYSQLLOG}/error.log
-			chmod 640 ${MYSQLLOG}/error.log
-			chown mysql:adm ${MYSQLLOG}/error.log
-		fi
-
-		if [ ! -d "${MYSQLRUN}" -a ! -L "${MYSQLRUN}" ];
-		then
-			mkdir ${MYSQLRUN}
-			chown mysql:mysql ${MYSQLRUN}
-			chmod 755 ${MYSQLRUN}
-		fi
-
-		/lib/init/apparmor-profile-load usr.sbin.mysqld
-
-		su - mysql -s /bin/bash -c "mysqld_safe > /dev/null &"
-		verify_server start
-		if [ "$?" -eq 0 ];
-		then
-			log_action_msg "MySQL Community Server ${VERSION} is started"
-		else
-			log_action_msg "MySQL Community Server ${VERSION} did not start. Please check logs for more details."
-		fi
+	    # 6s was reported in #352070 to be too few when using ndbcluster
+	    # 14s was reported in #736452 to be too few with large installs
+	    for i in $(seq 1 30); do
+                sleep 1
+	        if mysqld_status check_alive nowarn ; then break; fi
+		log_progress_msg "."
+	    done
+	    if mysqld_status check_alive warn; then
+                log_end_msg 0
+	        # Now start mysqlcheck or whatever the admin wants.
+	        output=$(/etc/mysql/debian-start)
+		[ -n "$output" ] && log_action_msg "$output"
+	    else
+	        log_end_msg 1
+		log_failure_msg "Please take a look at the syslog"
+	    fi
 	fi
 	;;
 
   'stop')
-	if [ "$(get_running)" -eq 1 ];
-	then
-		killall -u mysql
-		verify_server stop
-		if [ "$?" -eq 0 ];
-		then
-			log_action_msg "MySQL Community Server ${VERSION} is stopped"
-		else
-			log_action_msg "Attempt to shutdown MySQL Community Server ${VERSION} timed out"
-		fi
+	# * As a passwordless mysqladmin (e.g. via ~/.my.cnf) must be possible
+	# at least for cron, we can rely on it here, too. (although we have 
+	# to specify it explicit as e.g. sudo environments points to the normal
+	# users home and not /root)
+	log_daemon_msg "Stopping MySQL database server" "mysqld"
+	if ! mysqld_status check_dead nowarn; then
+	  set +e
+	  shutdown_out=`$MYADMIN shutdown 2>&1`; r=$?
+	  set -e
+	  if [ "$r" -ne 0 ]; then
+	    log_end_msg 1
+	    [ "$VERBOSE" != "no" ] && log_failure_msg "Error: $shutdown_out"
+	    log_daemon_msg "Killing MySQL database server by signal" "mysqld"
+	    killall -15 mysqld
+            server_down=
+	    for i in 1 2 3 4 5 6 7 8 9 10; do
+              sleep 1
+              if mysqld_status check_dead nowarn; then server_down=1; break; fi
+            done
+          if test -z "$server_down"; then killall -9 mysqld; fi
+	  fi
+        fi
+
+        if ! mysqld_status check_dead warn; then
+	  log_end_msg 1
+	  log_failure_msg "Please stop MySQL manually and read /usr/share/doc/mysql-server-5.7/README.Debian.gz!"
+	  exit -1
 	else
-		log_action_msg "MySQL Community Server ${VERSION} is already stopped"
-	fi
+	  log_end_msg 0
+        fi
 	;;
 
-  'restart'|'reload'|'force-reload')
-	log_action_msg "Stopping MySQL Community Server ${VERSION}"
-	$0 stop
-	log_action_msg "Re-starting MySQL Community Server ${VERSION}"
-	$0 start
+  'restart')
+	set +e; $SELF stop; set -e
+	$SELF start 
+	;;
+
+  'reload'|'force-reload')
+  	log_daemon_msg "Reloading MySQL database server" "mysqld"
+	$MYADMIN reload
+	log_end_msg 0
 	;;
 
   'status')
-	if [ "$(get_running)" -eq 1 ];
-	then
-		log_action_msg "MySQL Community Server ${VERSION} is running"
+	if mysqld_status check_alive nowarn; then
+	  log_action_msg "$($MYADMIN version)"
 	else
-		log_action_msg "MySQL Community Server ${VERSION} is not running"
-		exit 3
+	  log_action_msg "MySQL is stopped."
+	  exit 3
 	fi
-	;;
+  	;;
 
   *)
 	echo "Usage: $SELF start|stop|restart|reload|force-reload|status"
@@ -208,4 +186,6 @@ case "$1" in
 	;;
 esac
 
+# Some success paths end up returning non-zero so exit 0 explicitly. See
+# bug #739846.
 exit 0
