Changed upgrade logic
* Disabled most of it, since 5.6->5.7 really requires mysql_upgrade to be run
https://bugs.mysql.com/bug.php?id=78374 can also cause CREATE USER IF NOT EXISTS to fail

* Added notice about running mysql_upgrade if non-5.7 flag is detected

diff --git a/debian/mysql-server-5.7.postinst b/debian/mysql-server-5.7.postinst
--- a/debian/mysql-server-5.7.postinst
+++ b/debian/mysql-server-5.7.postinst
@@ -117,6 +117,11 @@ case "$1" in
     if ! set_mysql_rootpw; then
         password_error="yes"
     fi
+    ## On every reconfiguration the maintenance user is recreated.
+    #
+    # - It is easier to regenerate the password every time but as people
+    #   use fancy rsync scripts and file alteration monitors, the existing
+    #   password is used and existing files not touched.
     # recreate the credentials file if not present or without mysql_upgrade stanza
     dc=$mysql_cfgdir/debian.cnf; 
     if [ -e "$dc" -a -n "`fgrep mysql_upgrade $dc 2>/dev/null`" ]; then
@@ -162,35 +167,27 @@ case "$1" in
     echo "SHUTDOWN;" >> $tfile
 
     set +e
+    # TODO: 5.7 introduces significant changes to system tables when compared to earlier server versions
+    # Changes should not be made without running mysql_upgrade first and it requires a valid login to a
+    # running server, so it's generally something the user must handle themselves. One thing we can do
+    # is check if the 5.7 flag is present, which would indicate that changes can be made safely.
     if [ ! "$(ls -A ${mysql_statedir})" ] && [ -d ${mysql_filesdir} ]; then
       mysqld --initialize-insecure --user=mysql > /dev/null 2>&1
       run_init_sql $tfile
+    else # MySQL Bug #78374: CREATE user IF NOT EXISTS returns error instead of warning if user exists
+      if [ -f $mysql_statedir/debian-5.7.flag ]; then
+        echo
+        #run_init_sql $tfile
+      else
+        db_input medium mysql-server/upgrade-warning || true
+      fi
     fi
+
     rm $tfile
-    
     set -e
-    #invoke start
+
     # To avoid downgrades.
     touch $mysql_statedir/debian-5.7.flag
-
-    ## On every reconfiguration the maintenance user is recreated.
-    #
-    # - It is easier to regenerate the password every time but as people
-    #   use fancy rsync scripts and file alteration monitors, the existing
-    #   password is used and existing files not touched.
-    # - The mysqld statement is like that in mysql_install_db because the
-    #   server is not already running. This has some implications:
-    #   - The amount of newlines and semicolons in the query is important!
-    #   - GRANT is not possible with --skip-grant-tables and "INSERT
-    #     (user,host..) VALUES" is not --ansi compliant
-    # - The echo is just for readability. ash's buildin has no "-e" so use /bin/echo.
-    # - The Super_priv, Show_db_priv, Create_tmp_table_priv and Lock_tables_priv
-    #   may not be present as old Woody 3.23 databases did not have it and the
-    #   admin might not already have run mysql_upgrade which adds them.
-    #   As the binlog cron scripts to need at least the Super_priv, I do first
-    #   the old query which always succeeds and then the new which may or may not.
-
-
 
   ;;
 
@@ -208,21 +205,27 @@ esac
 # password wasn't set.  if there is a password, or if the connection
 # fails for any other reason, nothing happens.
 if [ "$1" = "configure" ]; then
-       if test_mysql_access; then
-               db_input medium mysql-server/root_password || true
-               db_go
-               db_get mysql-server/root_password && rootpw="$RET"
-
-               if ! set_mysql_rootpw "online"; then
-                       password_error="yes"
-               fi
-       fi
-
-       if [ "$password_error" = "yes" ]; then
-               db_input high mysql-server/error_setting_password || true
-               db_go
-       fi
-
+  if test_mysql_access; then
+    echo "We recommend setting a password for the root user."
+#    db_input medium mysql-server/root_password || true
+#    db_go
+#    db_get mysql-server/root_password && rootpw="$RET"
+#    touch $tfile
+#    chmod 600 $tfile
+#    chown mysql:mysql $tfile
+#    echo "USE mysql; " >> $tfile
+#    if [ ! -z $rootpw ]; then
+#      echo "UPDATE user SET authentication_string=PASSWORD('$rootpw') WHERE user='root';" >> $tfile
+#    else # TODO: Check if the need for the password_expired change is upstream bug
+#      echo "INSTALL PLUGIN auth_socket SONAME 'auth_socket.so';" >> $tfile # Will throw an error if plugin already exists
+#      echo "ALTER USER 'root'@'localhost' IDENTIFIED WITH 'auth_socket';" >> $tfile
+#      echo "UPDATE mysql.user SET password_expired='N' WHERE user='root';" >> $tfile
+#    fi
+#    set +e
+#    run_init_sql $tfile
+#    set -e
+#    rm $tfile
+  fi
 fi
 
 db_stop # in case invoke failes
