Cleaned up postinst script
* Fixed whitespace issues
* Moved password changing to common routine
* Removed auth_socket

diff --git a/debian/mysql-server-5.7.postinst b/debian/mysql-server-5.7.postinst
--- a/debian/mysql-server-5.7.postinst
+++ b/debian/mysql-server-5.7.postinst
@@ -42,11 +42,20 @@ test_sysmaint_access() {
   mysql --defaults-file=/etc/mysql/debian.cnf </dev/null >/dev/null 2>&1
 }
 
-# call with $1 = "online" to connect to the server, otherwise it bootstraps
-set_mysql_rootpw() {
-       # forget we ever saw the password.  don't use reset to keep the seen status
-       db_set mysql-server/root_password ""
-       db_set mysql-server/root_password_again ""
+# $1 should be username, e.g. 'root' $2 is password
+set_mysql_pw() {
+  user="$1"
+  pass="$2"
+  passfile=/var/lib/mysql-files/passchange
+  touch $passfile
+  chmod 600 $passfile
+  chown mysql:mysql $passfile
+  echo "USE mysql;" >> $passfile
+  echo "UPDATE user SET authentication_string=PASSWORD('$pass') WHERE user='$user';" >> $passfile
+  echo "FLUSH PRIVILEGES;" >> $passfile
+  echo "SHUTDOWN;" >> $passfile
+  run_init_sql $passfile
+  rm $passfile
 }
 
 # This is necessary because mysql_install_db removes the pid file in /var/run
@@ -76,13 +85,13 @@ case "$1" in
     #
     # This a workaround. Status is tracked at https://launchpad.net/bugs/1435368
     if aa-status --enabled 2>/dev/null; then
-    # It is common for this to fail because
-    # /etc/apparmor.d/local/usr.sbin.mysqld doesn't exist (eg. on first
-    # install). But if this happens, then the workaround is not required,
-    # so it doesn't matter. If instead it causes a security issue, then
-    # that doesn't really matter here as dh_apparmor should handle that
-    # correctly later on.
-        apparmor_parser -r -T -W /etc/apparmor.d/usr.sbin.mysqld 2>/dev/null || true
+      # It is common for this to fail because
+      # /etc/apparmor.d/local/usr.sbin.mysqld doesn't exist (eg. on first
+      # install). But if this happens, then the workaround is not required,
+      # so it doesn't matter. If instead it causes a security issue, then
+      # that doesn't really matter here as dh_apparmor should handle that
+      # correctly later on.
+      apparmor_parser -r -T -W /etc/apparmor.d/usr.sbin.mysqld 2>/dev/null || true
     fi
 
     # New packaging paradigm for my.cnf as of Dec-2014 for sharing mysql
@@ -118,13 +127,6 @@ case "$1" in
     # data directory and then somewhen gets purged by the admin.
     db_set mysql-server/postrm_remove_database false || true
 
-
-    # initiate databases. Output is not allowed by debconf :-(
-    # Debian: can safely run on upgrades with existing databases
-    db_get mysql-server/root_password && rootpw="$RET"
-    if ! set_mysql_rootpw; then
-        password_error="yes"
-    fi
     ## On every reconfiguration the maintenance user is recreated.
     #
     # - It is easier to regenerate the password every time but as people
@@ -133,79 +135,70 @@ case "$1" in
     # recreate the credentials file if not present or without mysql_upgrade stanza
     dc=$mysql_cfgdir/debian.cnf; 
     if [ -e "$dc" -a -n "`fgrep mysql_upgrade $dc 2>/dev/null`" ]; then
-        pass="`sed -n 's/^[     ]*password *= *// p' $dc | head -n 1`"
-        sed -i '/basedir/d' "$dc"
+      pass="`sed -n 's/^[     ]*password *= *// p' $dc | head -n 1`"
+      # Basedir is deprecated. Remove the option if it's in an existing debian.cnf
+      sed -i '/basedir/d' "$dc"
     else
-    pass=`perl -e 'print map{("a".."z","A".."Z",0..9)[int(rand(62))]}(1..16)'`;
-        if [ ! -d "$mysql_cfgdir" ]; then install -o 0 -g 0 -m 0755 -d $mysql_cfgdir; fi
-        umask 066
-        cat /dev/null > $dc
-        umask 022
-        echo "# Automatically generated for Debian scripts. DO NOT TOUCH!" >>$dc
-        echo "[client]"                                                    >>$dc
-        echo "host     = localhost"                                        >>$dc
-        echo "user     = debian-sys-maint"                                 >>$dc
-        echo "password = $pass"                                            >>$dc
-        echo "socket   = $mysql_rundir/mysqld.sock"                        >>$dc
-        echo "[mysql_upgrade]"                                             >>$dc
-        echo "host     = localhost"                                        >>$dc
-        echo "user     = debian-sys-maint"                                 >>$dc
-        echo "password = $pass"                                            >>$dc
-        echo "socket   = $mysql_rundir/mysqld.sock"                        >>$dc
+      pass=`perl -e 'print map{("a".."z","A".."Z",0..9)[int(rand(62))]}(1..16)'`;
+      if [ ! -d "$mysql_cfgdir" ]; then install -o 0 -g 0 -m 0755 -d $mysql_cfgdir; fi
+      umask 066
+      cat /dev/null > $dc
+      umask 022
+      echo "# Automatically generated for Debian scripts. DO NOT TOUCH!" >>$dc
+      echo "[client]"                                                    >>$dc
+      echo "host     = localhost"                                        >>$dc
+      echo "user     = debian-sys-maint"                                 >>$dc
+      echo "password = $pass"                                            >>$dc
+      echo "socket   = $mysql_rundir/mysqld.sock"                        >>$dc
+      echo "[mysql_upgrade]"                                             >>$dc
+      echo "host     = localhost"                                        >>$dc
+      echo "user     = debian-sys-maint"                                 >>$dc
+      echo "password = $pass"                                            >>$dc
+      echo "socket   = $mysql_rundir/mysqld.sock"                        >>$dc
     fi
     # If this dir chmod go+w then the admin did it. But this file should not.
     chown 0:0 $dc
     chmod 0600 $dc
-   
-    tfile=/var/lib/mysql-files/SQL
-    touch $tfile
-    chmod 600 $tfile
-    chown mysql:mysql $tfile
-    echo "USE mysql; " >> $tfile
-    if [ ! -z $rootpw ]; then  
-      echo "UPDATE user SET authentication_string=PASSWORD('$rootpw') WHERE user='root';" >> $tfile
-    else # TODO: Check if the need for the password_expired change is upstream bug
-      echo "select 1;"
-      #echo "INSTALL PLUGIN auth_socket SONAME 'auth_socket.so';" >> $tfile
-      #echo "ALTER USER 'root'@'localhost' IDENTIFIED WITH 'auth_socket';" >> $tfile
-      #echo "UPDATE mysql.user SET password_expired='N' WHERE user='root';" >> $tfile
-    fi
-    echo "CREATE user IF NOT EXISTS 'debian-sys-maint'@'localhost' IDENTIFIED BY '$pass';" >> $tfile
-    echo "GRANT ALL ON *.* TO 'debian-sys-maint'@'localhost';" >> $tfile
-    echo "FLUSH PRIVILEGES;" >> $tfile
-    echo "SHUTDOWN;" >> $tfile
 
+    # initiate databases. Output is not allowed by debconf :-(
+    # Debian: can safely run on upgrades with existing databases
     # If database doesn't exist we create it. Otherwise we run mysql_upgrade
     set +e
     if [ ! "$(ls -A ${mysql_statedir})" ] && [ -d ${mysql_filesdir} ]; then
-      mysqld --initialize-insecure --user=mysql --init-file=$tfile> /dev/null 2>&1
+      initfile=/var/lib/mysql-files/SQL
+      touch $initfile
+      chmod 600 $initfile
+      chown mysql:mysql $initfile
+      echo "USE mysql; " >> $initfile
+      db_get mysql-server/root_password && rootpw="$RET"
+      # forget we ever saw the password.  don't use reset to keep the seen status
+      db_set mysql-server/root_password ""
+      db_set mysql-server/root_password_again ""
+      if [ ! -z $rootpw ]; then
+        echo "ALTER user 'root'@'localhost' IDENTIFIED BY '$rootpw';" >> $initfile
+      fi
+      echo "CREATE user IF NOT EXISTS 'debian-sys-maint'@'localhost' IDENTIFIED BY '$pass';" >> $initfile
+      echo "GRANT ALL ON *.* TO 'debian-sys-maint'@'localhost';" >> $initfile
+      echo "FLUSH PRIVILEGES;" >> $initfile
+      echo "SHUTDOWN;" >> $initfile
+      mysqld --initialize-insecure --user=mysql --init-file=$initfile> /dev/null 2>&1
     else
       invoke start
       if test_sysmaint_access; then
         mysql_upgrade --defaults-file=/etc/mysql/debian.cnf
       else # In case the debian user can't log in we try setting the password
         invoke stop
-        maintfile=/var/lib/mysql-files/Update-sysmaint
-        touch $maintfile
-        chmod 600 $maintfile
-        chown mysql:mysql $maintfile
-        echo "USE mysql;" >> $maintfile
-        echo "UPDATE mysql.user SET authentication_string=PASSWORD('$pass') WHERE user='debian-sys-maint';" >> $maintfile
-        echo "FLUSH PRIVILEGES;" >> $maintfile
-        echo "SHUTDOWN;" >> $maintfile
-        set +e
-        run_init_sql $maintfile
-        rm $maintfile
+        set_mysql_pw "debian-sys-maint" "$pass"
         invoke start
         mysql_upgrade --defaults-file=/etc/mysql/debian.cnf 
       fi
     fi
     
     invoke stop
-    rm $tfile
+    rm $initfile
     set -e
 
-    # To avoid downgrades.
+    # To avoid downgrades. This has to happen after the database is created, or --initialize will fail
     touch $mysql_statedir/debian-5.7.flag
 
   ;;
@@ -229,11 +222,7 @@ if [ "$1" = "configure" ]; then
     db_go
     db_get mysql-server/root_password && rootpw="$RET"
     if [ ! -z $rootpw ]; then
-      touch $tfile
-      chmod 600 $tfile
-      chown mysql:mysql $tfile
-      echo "ALTER USER 'root'@'localhost' IDENTIFIED BY '$rootpw';" >> $tfile
-      run_init_sql $tfile
+      set_mysql_pw 'root' $rootpw
     fi
   fi
 fi
